set nocompatible
filetype off
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
" Colorscheme
Plug 'gryf/wombat256grf'
Plug 'sheerun/vim-polyglot'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
" Yaml formatting
" Plug 'tarekbecker/vim-yaml-formatter'
call plug#end()

syntax on

"colorscheme wombat256grf
"colorscheme onedark
"colorscheme slate
"colorscheme molokai
let g:zenburn_high_Contrast=1
" For black background
"let g:zenburn_transparent=1
colorscheme zenburn

" trim trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

set number

" Indentation
" show existing tab with 4 spaces width
set tabstop=4
set softtabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

"set autoindent

au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.js,*.html,*.css,*.sh
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufNewFile,BufRead [Mm]akefile
    \ set expandtab!

" alias W and Wq for shift typos
:command W w
:command Wq wq

